server:
  port: 8081

spring:
  
  datasource:
    url: jdbc:mysql://localhost:3306/db_banque?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: haroun
    password: passer
    driverClassName: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  
